<?php

/**
 * Running PHPUnit tests.
 * Define necessary constands.
 * Register composer autoloader.
 */

define('ROOT_DIR', realpath(__DIR__ . '/../..'));
define('LIBS_DIR', realpath(ROOT_DIR . '/Libs'));
define('APP_DIR', realpath(ROOT_DIR . '/PhpMinifi'));
define('FIXTURES_DIR', realpath(ROOT_DIR . '/Tests/Unit/Fixtures'));

// Autoloader generated by Composer
$loader = require LIBS_DIR . '/autoload.php';
$loader->add(NULL, array(APP_DIR));

// run phpunit
require_once LIBS_DIR . '/phpunit/phpunit/phpunit.php';
